### ISSUE TITLE
Catch & handle protocol/network-related errors

### ISSUE THREAD

**Issue by rc0r** [rc0r/AvivoreXT#7]
Catch exceptions caused by HTTP/HTTPS protocol or general network errors in order to avoid Avivore crashes due to simple time outs.

**Comment by rc0r** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/pi/dev/python/AvivoreXT/venv/local/lib/python2.7/site-packages/AvivoreXT-1.2.3-py2.7.egg/AvivoreXT/avivore.py", line 279, in run
    twitter_query_main(self.avivore)
  File "/home/pi/dev/python/AvivoreXT/venv/local/lib/python2.7/site-packages/AvivoreXT-1.2.3-py2.7.egg/AvivoreXT/avivore.py", line 318, in twitter_query_main
    twit_data = avivore.twitter_search(x)
  File "/home/pi/dev/python/AvivoreXT/venv/local/lib/python2.7/site-packages/AvivoreXT-1.2.3-py2.7.egg/AvivoreXT/avivore.py", line 197, in twitter_search
    search_results = self.twitter_instance.search.tweets(q=search_string)
  File "/home/pi/dev/python/AvivoreXT/venv/local/lib/python2.7/site-packages/twitter-1.15.0-py2.7.egg/twitter/api.py", line 266, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/home/pi/dev/python/AvivoreXT/venv/local/lib/python2.7/site-packages/twitter-1.15.0-py2.7.egg/twitter/api.py", line 273, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1219, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
