### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by rc0r** [rc0r/AvivoreXT#9]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "./avivore.py", line 268, in run
    twitter_query_main(self.avivore)
  File "./avivore.py", line 322, in twitter_query_main
    string = result[0], z[2], str(result[1]), z[0], z[3], z[4]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 7: ordinal not in range(128)

**Comment by rc0r** [comment]
Testing done, fixed in [`a2b8782`](https://github.com/rc0r/AvivoreXT/commit/a2b878275cf09df44e4b216849b1aeeb04b3448a).
